all: udp_broadcast_server.c udp_broadcast_client.c udp_multicast_server.c udp_multicast_client.c
	gcc -o ubs udp_broadcast_server.c
	gcc -o ubc udp_broadcast_client.c
	gcc -o ums udp_multicast_server.c
	gcc -o umc udp_multicast_client.c